[msg pc_stu_rank_up_msg_00]
[s]Your [f 4 11 0][clr 26][f 4 12 0][clr 27] has increased[n]from [var 1] to [clr 26][var 2][clr 27]![n][w][e]

[msg pc_stu_rank_up_msg_01]
[s]Your [f 4 11 1][clr 26][f 4 12 1][clr 27] has increased[n]from [var 1] to [clr 26][var 2][clr 27]![n][w][e]

[msg pc_stu_rank_up_msg_02]
[s]Your [f 4 11 2][clr 26][f 4 12 2][clr 27] has increased[n]from [var 1] to [clr 26][var 2][clr 27]![n][w][e]

[msg pc_stu_rank_up_msg_03]
[s]Your [f 4 11 3][clr 26][f 4 12 3][clr 27] has increased[n]from [var 1] to [clr 26][var 2][clr 27]![n][w][e]

[msg pc_stu_rank_up_msg_04]
[s]Your [f 4 11 4][clr 26][f 4 12 4][clr 27] has increased[n]from [var 1] to [clr 26][var 2][clr 27]![n][w][e]

[msg pc_stu_param_up_msg_00]
[s][f 4 3]'s[n][f 4 11 0][clr 26][f 4 12 0][clr 27] has improved![n][w][e]

[msg pc_stu_param_up_msg_01]
[s][f 4 3]'s[n][f 4 11 1][clr 26][f 4 12 1][clr 27] has improved![n][w][e]

[msg pc_stu_param_up_msg_02]
[s][f 4 3]'s[n][f 4 11 2][clr 26][f 4 12 2][clr 27] has improved![n][w][e]

[msg pc_stu_param_up_msg_03]
[s][f 4 3]'s[n][f 4 11 3][clr 26][f 4 12 3][clr 27] has improved![n][w][e]

[msg pc_stu_param_up_msg_04]
[s][f 4 3]'s[n][f 4 11 4][clr 26][f 4 12 4][clr 27] has improved![n][w][e]

[msg commu00_lv01]
[s]BLANK 1[n][e]

[msg commu00_lv02]
[s]BLANK 2[n][e]

[msg commu00_lv03]
[s]BLANK 3[n][e]

[msg commu00_lv04]
[s]BLANK 4[n][e]

[msg commu00_lv05]
[s]BLANK 5[n][e]

[msg commu00_lv06]
[s]BLANK 6[n][e]

[msg commu00_lv07]
[s]BLANK 7[n][e]

[msg commu00_lv08]
[s]BLANK 8[n][e]

[msg commu00_lv09]
[s]BLANK 9[n][e]

[msg commu00_lv10]
[s]BLANK 10[n][e]

[msg commu00_rev]
[s]BLANK DOUBT[n][e]

[msg commu00_broken]
[s]BLANK BROKEN[n][e]

[msg commu01_help]
[s]Fool Arcana Burst.[n]Aids you in thievery skills[n]and Persona fusion.[n][e]

[msg commu01_lv01]
[s]The odd-nosed master of the[n]prison. He has told you to[n]form bonds with others...[n][e]

[msg commu01_lv02]
[s]He has unlocked Persona[n]Fusion in expectation of[n]your rehabilitation...[n][e]

[msg commu01_lv03]
[s]He praised your success in[n]conquering the first Palace. He[n]is satisfied with your progress...[n][e]

[msg commu01_lv04]
[s]He praised you for success in[n]the second Palace, but warned of[n]someone else in the Metaverse...[n][e]

[msg commu01_lv05]
[s]He said that deepening bonds[n]with society's outcasts would[n]lead to more power...[n][e]

[msg commu01_lv06]
[s]He predicted you will meet the[n]mysterious infiltrator soon,[n]but seems to be enjoying this...[n][e]

[msg commu01_lv07]
[s]He warned you to be wary[n]of the person who stole[n]data on the Metaverse...[n][e]

[msg commu01_lv08]
[s]He is satisfied that your[n]rehabilitation is ending soon.[n]However, fate is taking a turn...[n][e]

[msg commu01_lv09]
[s]Just as anticipated, a sudden[n]predicament has arisen. He says[n]that you must overcome it...[n][e]

[msg commu01_lv10]
[s]True Igor has returned, making[n]you a true guest of the Velvet[n]Room. The final battle awaits...[n][e]

[msg commu01_rev]
[s]Igor Doubt[n]This is a bug.[n][e]

[msg commu01_broken]
[s]Igor Broken[n]This is a bug.[n][e]

[msg commu02_help]
[s]Magician Arcana Burst.[n]Teaches how to make infiltration[n]tools and bestows battle skills.[n][e]

[msg commu02_lv01]
[s]A mysterious being you[n]met in the Metaverse who[n]claims to be a former human...[n][e]

[msg commu02_lv02]
[s]A mysterious cat(?) who is[n]familiar with the Metaverse.[n]You seem promising...[n][e]

[msg commu02_lv03]
[s]As he talked about becoming[n]human once again, you were able[n]to hear his inner thoughts...[n][e]

[msg commu02_lv04]
[s]The phrase "take somewhere"[n]seems to have triggered[n]something in his memory...[n][e]

[msg commu02_lv05]
[s]He showed his weak side,[n]but swallowed his words.[n]Who is he really...?[n][e]

[msg commu02_lv06]
[s]He is full of spirit and[n]hopes that returning to human[n]form will restore his memory...[n][e]

[msg commu02_lv07]
[s]A nightmare made him think he[n]could be a monster. Fixing[n]Mementos should solve it, but...[n][e]

[msg commu02_lv08]
[s]He has realized that he wants[n]to be with you simply because[n]your trust has deepened...[n][e]

[msg commu02_lv09]
[s]He has found purpose in[n]carrying out the objectives[n]of the Phantom Thieves.[n][e]

[msg commu02_lv10]
[s]He has realized he belongs where[n]you belong. It does not matter[n]who he was; he is a true comrade.[n][e]

[msg commu02_rev]
[s]Morgana Doubt[n]This is a bug.[n][e]

[msg commu02_broken]
[s]Morgana Broken[n]This is a bug.[n][e]

[msg commu03_help]
[s]High Priestess Arcana Burst.[n]Allows for Shadow analysis[n]and bestows battle skills.[n][e]

[msg commu03_lv01]
[s]After experiencing the arcade[n]to broaden her views, she wants[n]to go to the red-light district.[n][e]

[msg commu03_lv02]
[s]After getting exhausted at the[n]red-light district, she saw a[n]Shujin student at a shady store...[n][e]

[msg commu03_lv03]
[s]While talking with Eiko, she[n]was shocked to be dismissed[n]as an honor student...[n][e]

[msg commu03_lv04]
[s]Unsure of the point of studying[n]anymore, she talked about her[n]memories of her father.[n][e]

[msg commu03_lv05]
[s]Worrying about the character of[n]Eiko's boyfriend, she planned[n]a double date to check him out.[n][e]

[msg commu03_lv06]
[s]She is still suspicious of[n]Eiko's boyfriend and wants to[n]understand how they think...[n][e]

[msg commu03_lv07]
[s]She mentioned the possibility[n]of human trafficking, and notes[n]how her father died on duty...[n][e]

[msg commu03_lv08]
[s]Her worry for Eiko has been[n]causing tension, but she is[n]determined to expose Tsukasa...[n][e]

[msg commu03_lv09]
[s]After exposing the host,[n]you have decided to help[n]Makoto study romance...[n][e]

[msg commu03_lv10]
[s]Supporting her dream to become[n]a police commissioner, you[n]hold her close as your lover...[n][e]

[msg commu03_rev]
[s]Makoto Doubt[n]This is a bug.[n][e]

[msg commu03_broken]
[s]Makoto Broken[n]This is a bug.[n][e]

[msg commu04_help]
[s]Empress Arcana Burst.[n]Allows for plant-growing[n]and bestows battle skills.[n][e]

[msg commu04_lv01]
[s]She raises plants for the team.[n]While worried about her company,[n]she has no one to trust...[n][e]

[msg commu04_lv02]
[s]She wants to grow coffee beans.[n]The new president seems to[n]make her suspicious...[n][e]

[msg commu04_lv03]
[s]She spoke about her desire[n]to cut ties with her fiancé[n]and find true love...[n][e]

[msg commu04_lv04]
[s]The new president seemed nice[n]enough, after meeting at the[n]hotel. What are his intentions...?[n][e]

[msg commu04_lv05]
[s]It seems the president wants[n]Haru to marry her fiancé for[n]the sake of the company...[n][e]

[msg commu04_lv06]
[s]She spoke of her grandfather's[n]coffee, and her fiancé revealed[n]wedding plans and walked away...[n][e]

[msg commu04_lv07]
[s]Skeptical about the company's[n]coffee venture, she decided[n]to talk with the new president.[n][e]

[msg commu04_lv08]
[s]She has asked you to accompany[n]her when she serves her coffee[n]to the new president.[n][e]

[msg commu04_lv09]
[s]Free from her fiancé after[n]speaking with the president,[n]she became your lover...[n][e]

[msg commu04_lv10]
[s]She dreams of owning a café.[n]Her gaze is focused on the[n]future, with a new fiancé...[n][e]

[msg commu04_rev]
[s]Haru Doubt[n]This is a bug.[n][e]

[msg commu04_broken]
[s]Haru Broken[n]This is a bug.[n][e]

[msg commu05_help]
[s]Emperor Arcana Burst.[n]Allows for Skill Card copying[n]and bestows battle skills.[n][e]

[msg commu05_lv01]
[s]In a slump, he has asked[n]for your help in finding[n]a new style...[n][e]

[msg commu05_lv02]
[s]He is showing confidence[n]in his passionate painting[n]created in Mementos...[n][e]

[msg commu05_lv03]
[s]His painting was poorly[n]received... Time to start over[n]in pulling him out of his slump.[n][e]

[msg commu05_lv04]
[s]He tried his hand at "love"[n]and failed. However, he seems[n]to have caught on to something...[n][e]

[msg commu05_lv05]
[s]He attempted a religious[n]painting. "Anguish" was[n]the subject, but...[n][e]

[msg commu05_lv06]
[s]While visiting Madarame's[n]house, an older gentleman[n]made him an offer...[n][e]

[msg commu05_lv07]
[s]He declined the offer[n]of support due to[n]dishonest motives...[n][e]

[msg commu05_lv08]
[s]His friends gave him advice[n]when he suddenly thought of[n]something and left...[n][e]

[msg commu05_lv09]
[s]Realizing the love infused[n]into his mother's painting,[n]he took hold of his brush...[n][e]

[msg commu05_lv10]
[s]His new work is titled "Desire[n]and Hope"... He now understands[n]the complexity of the heart.[n][e]

[msg commu05_rev]
[s]Yusuke Doubt[n]This is a bug.[n][e]

[msg commu05_broken]
[s]Yusuke Broken[n]This is a bug.[n][e]

[msg commu06_help]
[s]Hierophant Arcana Burst.[n]Teaches coffee-making skills.[n]There are other things to learn...[n][e]

[msg commu06_lv01]
[s]He has agreed to teach you[n]how to brew coffee if you[n]help him with the café.[n][e]

[msg commu06_lv02]
[s]A mysterious man appeared,[n]speaking of "curry" and "her"...[n][e]

[msg commu06_lv03]
[s]He suddenly ran out after[n]receiving a call from an[n]unknown number...[n][e]

[msg commu06_lv04]
[s]It seems he is being hounded for[n]money by the mysterious man,[n]who appears to be a relative...[n][e]

[msg commu06_lv05]
[s]He has revealed that Futaba's[n]mother was the inventor of[n]the curry recipe...[n][e]

[msg commu06_lv06]
[s]That greedy man was Futaba's[n]relative. Sojiro does not[n]trust him to be her guardian...[n][e]

[msg commu06_lv07]
[s]After clashing with Futaba,[n]he realized he was just[n]running away.[n][e]

[msg commu06_lv08]
[s]Futaba's uncle threatened to[n]press charges. Sojiro wishes[n]to defend the family...[n][e]

[msg commu06_lv09]
[s]Investigators came to review[n]the charges, but left with[n]confidence of your innocence.[n][e]

[msg commu06_lv10]
[s]At Futaba's mother's grave,[n]Sojiro gave you a smile from[n]the bottom of his heart.[n][e]

[msg commu06_rev]
[s]Sojiro Doubt[n]This is a bug.[n][e]

[msg commu06_broken]
[s]Sojiro Broken[n]This is a bug.[n][e]

[msg commu07_help]
[s]Lovers Arcana Burst.[n]Bestows negotiation skills[n]and battle skills.[n][e]

[msg commu07_lv01]
[s]She seeks revenge on Kamoshida.[n]With your goals aligned, you[n]decided to work together...[n][e]

[msg commu07_lv02]
[s]After visiting her friend, she[n]realized this was caused by her[n]weak heart, and vowed to train...[n][e]

[msg commu07_lv03]
[s]She wants to find ways to[n]strengthen her heart. Her[n]modeling career is busy too...[n][e]

[msg commu07_lv04]
[s]She decided to become an[n]action star, looking up to[n]the villainess she liked.[n][e]

[msg commu07_lv05]
[s]She burns with vengeance after[n]being outdone by another model[n]at a stand-in modeling gig...[n][e]

[msg commu07_lv06]
[s]Watching Shiho's recovery[n]efforts helped her realize[n]what true strength is.[n][e]

[msg commu07_lv07]
[s]Recognizing her lack of[n]professionalism, she vowed[n]to top the modeling world...[n][e]

[msg commu07_lv08]
[s]She started working toward[n]her goal, training at the[n]gym with Ryuji.[n][e]

[msg commu07_lv09]
[s]Seeing Shiho off, you stood[n]by her side as her lover,[n]comforting her...[n][e]

[msg commu07_lv10]
[s]She took on her rival in a[n]shoot. She wants to inspire[n]others, like her lover...[n][e]

[msg commu07_rev]
[s]Ann Doubt[n]This is a bug.[n][e]

[msg commu07_broken]
[s]Ann Broken[n]This is a bug.[n][e]

[msg commu08_help]
[s]Chariot Arcana Burst.[n]Bestows infiltration techniques[n]and battle skills.[n][e]

[msg commu08_lv01]
[s]On the verge of expulsion, you[n]decide to work together to[n]reclaim his place in school.[n][e]

[msg commu08_lv02]
[s]Though he feels guilty about[n]the track team disbanding,[n]he vows to train for you.[n][e]

[msg commu08_lv03]
[s]His former teammates appeared[n]before him, and he just took[n]it as they vented their anger...[n][e]

[msg commu08_lv04]
[s]Though still worried about[n]the track team, he said he[n]has the Phantom Thieves now.[n][e]

[msg commu08_lv05]
[s]He heard about the revival[n]of the track team, but worries[n]about their new advisor...[n][e]

[msg commu08_lv06]
[s]After seeing his former[n]teammates fight, he tried[n]to ask why, but...[n][e]

[msg commu08_lv07]
[s]He found out the new advisor[n]was the cause of the track[n]team's problems.[n][e]

[msg commu08_lv08]
[s]He told his former teammates[n]the truth, and successfully[n]got them to stop fighting.[n][e]

[msg commu08_lv09]
[s]He was asked to return to[n]the track team, but declared[n]he belongs here with us.[n][e]

[msg commu08_lv10]
[s]After facing his own[n]weakness, he vowed to[n]fight for his friends.[n][e]

[msg commu08_rev]
[s]Ryuji Doubt[n]This is a bug.[n][e]

[msg commu08_broken]
[s]Ryuji Broken[n]This is a bug.[n][e]

[msg commu09_help]
[s]Justice Arcana Burst.[n]Bestows the perceptiveness[n]of a detective.[n][e]

[msg commu09_lv01]
[s]While investigating the Phantom[n]Thieves, his "detective's intuition"[n]led him to [f 4 2]...[n][e]

[msg commu09_lv02]
[s]He invited you to play billiards.[n]What does he aim to accomplish[n]using his non-dominant hand...?[n][e]

[msg commu09_lv03]
[s]You helped him escape a close[n]call with fans of the popular[n]high school detective.[n][e]

[msg commu09_lv04]
[s]The Detective Prince invited you to[n]his go-to place, where you talked[n]a bit about your personal lives.[n][e]

[msg commu09_lv05]
[s]You played a shooting game[n]with him while talking about his[n]childhood dream of being a hero.[n][e]

[msg commu09_lv06]
[s]In the bathhouse, he discussed[n]his family and promised to play[n]another round of billiards.[n][e]

[msg commu09_lv07]
[s]After defeating him in a game[n]of billiards, he declares that he[n]won't hold back next time.[n][e]

[msg commu09_lv08]
[s]You fought Akechi in Mementos[n]and seized victory. He swore not[n]to lose to you again.[n][e]

[msg commu09_lv09]
[s]His objective is to get revenge[n]on his father, Shido. After[n]stating that, he attacked...[n][e]

[msg commu09_lv10]
[s]He sacrificed his own life in[n]order to save you... In the[n]end, your wishes became one.[n][e]

[msg commu09_rev]
[s]Akechi Doubt[n]This is a bug.[n][e]

[msg commu09_broken]
[s]Akechi Broken[n]This is a bug.[n][e]

[msg commu10_help]
[s]Hermit Arcana Burst.[n]Bestows informational[n]support skills.[n][e]

[msg commu10_lv01]
[s]Her rehabilitation in Akihabara[n]ended in failure. She needs you[n]by her side when she goes out.[n][e]

[msg commu10_lv02]
[s]She made a promise list,[n]allowing her to tackle[n]one task at a time...[n][e]

[msg commu10_lv03]
[s]She managed to succeed in her[n]rematch at Akihabara, but she[n]still needs your help...[n][e]

[msg commu10_lv04]
[s]Visiting your school, she[n]recalled her past, which she[n]is trying to overcome.[n][e]

[msg commu10_lv05]
[s]Thanks to Mishima, she has[n]completed two tasks at once.[n]Only one remains, but...[n][e]

[msg commu10_lv06]
[s]She confessed that she lied to[n]her mother about the promise[n]list, but wants to fulfill it now.[n][e]

[msg commu10_lv07]
[s]She began to worry, and asked[n]for help in Mementos to fix[n]her old friend's parents.[n][e]

[msg commu10_lv08]
[s]She promised her friend[n]she'd go to school. Only[n]one task remains...[n][e]

[msg commu10_lv09]
[s]Realizing her feelings are[n]love, she said she will do[n]her best as your girlfriend.[n][e]

[msg commu10_lv10]
[s]After conquering Akihabara,[n]she can do anything now...[n]even hang out with her lover.[n][e]

[msg commu10_rev]
[s]Futaba Doubt[n]This is a bug.[n][e]

[msg commu10_broken]
[s]Futaba Broken[n]This is a bug.[n][e]

[msg commu11_help]
[s]Fortune Arcana Burst.[n]Fortune telling will bring you[n]good luck if you do as told.[n][e]

[msg commu11_lv01]
[s]A sketchy fortune teller who[n]gives special fortunes if you[n]help with her fate tests.[n][e]

[msg commu11_lv02]
[s]Still unable to accept that[n]fate can be changed, she[n]continues to seek the test...[n][e]

[msg commu11_lv03]
[s]She finally accepted fate can[n]be changed, but lamented her[n]own unchangeable fate...[n][e]

[msg commu11_lv04]
[s]She feels doubt toward her[n]fraudulent business and gets[n]rid of the Holy Stone...[n][e]

[msg commu11_lv05]
[s]The chairman's assistant checks[n]up on her, the "Maiden," but she[n]does not explain her situation...[n][e]

[msg commu11_lv06]
[s]The chairman paid a visit, and[n]threatened she'd return to[n]being a monster if she leaves...[n][e]

[msg commu11_lv07]
[s]She continues to cling to the[n]"Maiden" name, but decided to[n]expose the chairman's fraud...[n][e]

[msg commu11_lv08]
[s]The chairman had a change of[n]heart, but she wants to save the[n]other brainwashed members.[n][e]

[msg commu11_lv09]
[s]As she continues to help the[n]confused members, you watch[n]over her as her lover...[n][e]

[msg commu11_lv10]
[s]She set herself a new future,[n]and vowed to guide her lover's[n]fate positively as well.[n][e]

[msg commu11_rev]
[s]Since doubt is cast upon me,[n]I can't have my fortune read...[n][e]

[msg commu11_broken]
[s]The deal is broken, so I can't[n]have my fortune read or get[n]the benefit of Arcana Burst...[n][e]

[msg commu12_help]
[s]In return for meeting quota,[n]they allow for flexibility[n]during Persona fusions.[n][e]

[msg commu12_lv01]
[s]They oppressively demanded[n]penal labor. You have no[n]choice but to obey...[n][e]

[msg commu12_lv02]
[s]They think highly of your will[n]to rehabilitate. You must keep[n]completing their tasks...[n][e]

[msg commu12_lv03]
[s]They seemed a bit flustered[n]after learning that the task[n]list's creator is unknown...[n][e]

[msg commu12_lv04]
[s]The mystery of the list[n]creator continues, but you[n]were still given a new task...[n][e]

[msg commu12_lv05]
[s]They were shaken upon seeing[n]the list's handwriting. Doing[n]this should solve everything...[n][e]

[msg commu12_lv06]
[s]Their memories are wavering[n]as they feel the nostalgia[n]of watching your growth...[n][e]

[msg commu12_lv07]
[s]They feel as if they're[n]losing something as you[n]complete your penal labor...[n][e]

[msg commu12_lv08]
[s]The task list's objective[n]was to change not the[n]prisoner, but the wardens...?[n][e]

[msg commu12_lv09]
[s]They now see that their goal[n]is to raise prisoners, and[n]you sense a bond with them...[n][e]

[msg commu12_lv10]
[s]Their memories did not return.[n]A bond going beyond prisoner[n]and wardens deepened instead.[n][e]

[msg commu12_rev]
[s]Twins Doubt[n]This is a bug.[n][e]

[msg commu12_broken]
[s]Twins Broken[n]This is a bug.[n][e]

[msg commu13_help]
[s]Hanged Man Arcana Burst. Provides[n]weapons and customization in[n]exchange for being his pawn.[n][e]

[msg commu13_lv01]
[s]Owner of an airsoft shop. He[n]can customize guns, but only if[n]you help with his shady work...[n][e]

[msg commu13_lv02]
[s]You gathered info for him,[n]and the "big deal" catches[n]his interest...[n][e]

[msg commu13_lv03]
[s]As former yakuza, he takes[n]risks to chase his former boss.[n]Surprisingly, he has a son...[n][e]

[msg commu13_lv04]
[s]His former boss brought up[n]his son as a threat, and[n]he plots to fight back...[n][e]

[msg commu13_lv05]
[s]He fears his son learning his[n]dark past. That fear continues[n]to be used as a threat...[n][e]

[msg commu13_lv06]
[s]As you ate dinner with his son,[n]he sensed his father braving[n]danger behind the scenes...[n][e]

[msg commu13_lv07]
[s]Grasping his former boss's[n]weakness, he asked you to be his[n]witness when he confronts him...[n][e]

[msg commu13_lv08]
[s]Now that the threats are no[n]longer an issue, he wants you to[n]help out with the shop again.[n][e]

[msg commu13_lv09]
[s]After the kidnapping, he told[n]the secrets to his son. Their[n]bond destroyed the enemy's plan.[n][e]

[msg commu13_lv10]
[s]Not liking the idea of owing[n]people favors, he promises to[n]give you powerful support.[n][e]

[msg commu13_rev]
[s]Since doubt is cast upon me,[n]he won't accept my requests[n]for customization...[n][e]

[msg commu13_broken]
[s]The deal is broken, so I can't[n]request customization or get[n]the benefit of Arcana Burst...[n][e]

[msg commu14_help]
[s]Death Arcana Burst. Provides[n]medicine if you act as a test[n]subject for clinical trials.[n][e]

[msg commu14_lv01]
[s]Doctor of a desolate clinic.[n]She can provide medicine if you[n]help with her clinical trials.[n][e]

[msg commu14_lv02]
[s]Her former boss sent a cop to[n]harass her, but that didn't[n]keep her from her research.[n][e]

[msg commu14_lv03]
[s]A call was dropped after her[n]name was said. Seems she's made[n]a medical error in the past...[n][e]

[msg commu14_lv04]
[s]Hearing the name of the girl's[n]previous doctor, she happily[n]gave her accurate treatment.[n][e]

[msg commu14_lv05]
[s]It seems she was blamed for the[n]medical error, but continues[n]to work on that medicine.[n][e]

[msg commu14_lv06]
[s]With her growing popularity as[n]the town doctor, she hopes to[n]finally complete the medicine.[n][e]

[msg commu14_lv07]
[s]She falls into depression after[n]hearing news about a patient[n]from the Chief of Staff...[n][e]

[msg commu14_lv08]
[s]She rushes to complete the[n]medicine after hearing that[n]her old patient is still alive.[n][e]

[msg commu14_lv09]
[s]Stocked with new data, she[n]declined the offer to work at a[n]hospital and became your lover...[n][e]

[msg commu14_lv10]
[s]As her lover, you continue to[n]support the town doctor and her[n]development of new medicines.[n][e]

[msg commu14_rev]
[s]Since doubt is cast upon me,[n]I can't buy any highly[n]effective medicine...[n][e]

[msg commu14_broken]
[s]The deal is broken, so I can't[n]buy any special medicine or get[n]the benefit of Arcana Burst...[n][e]

[msg commu15_help]
[s]Temperance Arcana Burst. Helps[n]with academics as a teacher,[n]and housework as a maid.[n][e]

[msg commu15_lv01]
[s]The secret maid teacher. She[n]offered to let you slack off[n]if you request her again...[n][e]

[msg commu15_lv02]
[s]She claimed to be struggling[n]with money due to her little[n]sister's medical expenses...[n][e]

[msg commu15_lv03]
[s]She hesitantly expressed needing[n]more work than ever to pay[n]off a huge amount of money...[n][e]

[msg commu15_lv04]
[s]She confessed that she lied[n]about the medical expenses and[n]says to stop requesting her.[n][e]

[msg commu15_lv05]
[s]She's been paying apology[n]money to take responsibility[n]for her former student's death...[n][e]

[msg commu15_lv06]
[s]She was asked for even more[n]money, so she's picking up more[n]shifts than she can handle...[n][e]

[msg commu15_lv07]
[s]Despite collapsing from[n]exhaustion, she keeps working[n]to meet the guardians' demands...[n][e]

[msg commu15_lv08]
[s]She remembered her duty as a[n]teacher, and decided to talk[n]things out with the guardians.[n][e]

[msg commu15_lv09]
[s]The guardians had a change of[n]heart. She quit being a maid and[n]wants a fresh start as a teacher.[n][e]

[msg commu15_lv10]
[s]As she fulfills her role[n]as a teacher, the two of[n]you become lovers...[n][e]

[msg commu15_rev]
[s]Since doubt is cast upon me,[n]I can't strike a deal[n]with Kawakami...[n][e]

[msg commu15_broken]
[s]The deal is broken, so I can't[n]strike a deal with Kawakami or[n]get the benefit of Arcana Burst...[n][e]

[msg commu16_help]
[s]Devil Arcana Burst. Articles[n]control public view of the Phantom[n]Thieves and change the Metaverse.[n][e]

[msg commu16_lv01]
[s]A journalist who can write[n]articles on the Phantom Thieves[n]based on information you give.[n][e]

[msg commu16_lv02]
[s]Due to a past incident, she was[n]taken off of politics and[n]still suffers unfair treatment.[n][e]

[msg commu16_lv03]
[s]She continues work to prove[n]her partner's innocence, but[n]won't share the details...[n][e]

[msg commu16_lv04]
[s]Her boss appeared, and you acted[n]quickly to hide her independent[n]investigation from him...[n][e]

[msg commu16_lv05]
[s]It seems she is trying to[n]prove her partner's innocence[n]in the death of a bureaucrat.[n][e]

[msg commu16_lv06]
[s]Her efforts were obstructed by[n]a superior, but she continues[n]to pursue the truth of the case.[n][e]

[msg commu16_lv07]
[s]Her higher-ups discovered[n]her efforts, and forced her[n]into a corner...[n][e]

[msg commu16_lv08]
[s]She discovered that her former[n]partner is in a mental hospital,[n]and decided to visit...[n][e]

[msg commu16_lv09]
[s]She finally unveiled the[n]mastermind behind the case,[n]and you became lovers...[n][e]

[msg commu16_lv10]
[s]You support your lover as she[n]works with the Phantom Thieves[n]to uncover social evils.[n][e]

[msg commu16_rev]
[s]Since doubt is cast upon me,[n]she won't accept my requests[n]to write articles...[n][e]

[msg commu16_broken]
[s]The deal is broken, so I can't[n]have her write articles or get[n]the benefit of Arcana Burst...[n][e]

[msg commu17_help]
[s]Tower Arcana Burst. Shinya's[n]teachings increase your[n]gun-shooting ability.[n][e]

[msg commu17_lv01]
[s]A skilled boy you met at[n]the arcade. He's agreed to[n]teach you how to shoot.[n][e]

[msg commu17_lv02]
[s]His obsession with winning[n]stems from his admiration[n]of the Phantom Thieves.[n][e]

[msg commu17_lv03]
[s]He was harassed at school due[n]to his mother, but he believes[n]it was because he is too weak.[n][e]

[msg commu17_lv04]
[s]He got destroyed by an adult[n]gamer. Unable to accept the[n]loss, he swears his revenge...[n][e]

[msg commu17_lv05]
[s]He voiced concerns about the[n]gamer's possible cheating to[n]his mother, but she doesn't care.[n][e]

[msg commu17_lv06]
[s]He realized that he was the[n]bad guy for extorting money[n]to play games.[n][e]

[msg commu17_lv07]
[s]Shocked by his mother's odd[n]behavior, he seeks help from[n]the Phantom Thieves.[n][e]

[msg commu17_lv08]
[s]Confused by the calling card[n]targeting his mother, he finally[n]decided to hand it to her...[n][e]

[msg commu17_lv09]
[s]After his mother's change of[n]heart, he himself changed and[n]stopped obsessing over winning.[n][e]

[msg commu17_lv10]
[s]After defeating the unfair gamer,[n]he made up with the other boys[n]and became a fine young man.[n][e]

[msg commu17_rev]
[s]Since doubt is cast upon me,[n]I can't get him to teach me[n]any new shooting skills...[n][e]

[msg commu17_broken]
[s]The deal is broken, so I can't[n]have shooting lessons or get[n]the benefit of Arcana Burst...[n][e]

[msg commu18_help]
[s]Star Arcana Burst. Concepts[n]learned from shogi bestow[n]special strategies in battle.[n][e]

[msg commu18_lv01]
[s]A shogi player who hangs out in[n]a church. She asked you to be[n]her test subject for new moves.[n][e]

[msg commu18_lv02]
[s]Although photoshoots have[n]increased her popularity, she[n]doesn't seem to enjoy it...[n][e]

[msg commu18_lv03]
[s]She does many interviews to[n]meet her mother's demands, but[n]is bothered by her attitude...[n][e]

[msg commu18_lv04]
[s]She expressed concern about[n]her senior's envy and her[n]reputation online.[n][e]

[msg commu18_lv05]
[s]She wants to please her mother,[n]but is distressed by the idol[n]status she is heading toward.[n][e]

[msg commu18_lv06]
[s]Despite the stress of privacy[n]invasion, she's intent on[n]continuing her beloved shogi.[n][e]

[msg commu18_lv07]
[s]She resolved to face a strong,[n]famous opponent in hopes[n]of escaping her idol status.[n][e]

[msg commu18_lv08]
[s]She decided to confess the set[n]up matches, but still intends to[n]play against the professional...[n][e]

[msg commu18_lv09]
[s]Realizing her lack of skill, she[n]tried to resign from teaching.[n]You pulled her back as a lover...[n][e]

[msg commu18_lv10]
[s]She decided to start fresh to[n]redeem herself, while you two[n]support each other as lovers.[n][e]

[msg commu18_rev]
[s]Since doubt is cast upon me,[n]I can't receive shogi lessons...[n][e]

[msg commu18_broken]
[s]The deal is broken, so I can't[n]receive shogi lessons or get[n]the benefit of Arcana Burst...[n][e]

[msg commu19_help]
[s]Moon Arcana Burst.[n]Provides requests through[n]the Phan-Site.[n][e]

[msg commu19_lv01]
[s]He created the Phan-Site[n]and is enthusiastic about[n]collecting intel on bad guys.[n][e]

[msg commu19_lv02]
[s]Calling himself the strategic[n]image management rep, he[n]tries to hype up the forum.[n][e]

[msg commu19_lv03]
[s]He tried to organize an offline[n]meeting but was stood up...[n][e]

[msg commu19_lv04]
[s]He invited you to dinner, but[n]you found out he was collecting[n]donations through his site...[n][e]

[msg commu19_lv05]
[s]After being made fun of by[n]former classmates, he said[n]that things are different now.[n][e]

[msg commu19_lv06]
[s]He set the next target as a[n]popular actor, but it seems[n]to be for personal reasons...[n][e]

[msg commu19_lv07]
[s]After his Shadow was persuaded,[n]he became ashamed of his actions[n]and renewed his vow to help.[n][e]

[msg commu19_lv08]
[s]After saving an old classmate[n]from bullies, he realized what[n]it means to be a phantom thief.[n][e]

[msg commu19_lv09]
[s]After being praised by his old[n]classmate, he revealed he is[n]making a documentary.[n][e]

[msg commu19_lv10]
[s]Realizing it's not power, but[n]heart, that changes the world,[n]he vows to do his best to help.[n][e]

[msg commu19_rev]
[s]Mishima Doubt[n]This is a bug.[n][e]

[msg commu19_broken]
[s]Mishima Broken[n]This is a bug.[n][e]

[msg commu20_help]
[s]Sun Arcana Burst. Working for[n]him teaches you negotiation[n]tactics for battle.[n][e]

[msg commu20_lv01]
[s]A former Dietman who considers[n]himself a failure. Helping him[n]may improve your speaking skills.[n][e]

[msg commu20_lv02]
[s]Haunted by a past trauma,[n]he was disturbed upon hearing[n]the name "No-Good Tora."[n][e]

[msg commu20_lv03]
[s]It appears he was blamed in[n]the past for misappropriation[n]of political party funds...[n][e]

[msg commu20_lv04]
[s]He stiffened up when called an[n]"ex-convict," but overcame the[n]complex when you backed him up.[n][e]

[msg commu20_lv05]
[s]He saw a sign of hope from the[n]grandson of his former mentor,[n]whom he was on bad terms with.[n][e]

[msg commu20_lv06]
[s]A Dietman offered to clear[n]Yoshida's false accusation if[n]he drops out of the election...[n][e]

[msg commu20_lv07]
[s]He refused a sweet deal and[n]keeps running. But the Dietman[n]had another secret...[n][e]

[msg commu20_lv08]
[s]He firmly refused the offer, and[n]decided to make his next speech[n]about the Phantom Thieves...[n][e]

[msg commu20_lv09]
[s]He mentioned nothing about the[n]false charge, which moved his[n]colleague to support his run.[n][e]

[msg commu20_lv10]
[s]He gained crowds of supporters[n]and stated he supports the youth[n]who try to reform the world...[n][e]

[msg commu20_rev]
[s]Since doubt is cast upon me,[n]I can't help with his speeches.[n][e]

[msg commu20_broken]
[s]Since the deal is broken, I can't[n]receive speech lessons nor receive[n]the benefit of Arcana Burst.[n][e]

[msg commu21_help]
[s]Judgement Arcana Burst.[n][e]

[msg commu21_lv01]
[s]She did not believe the[n]testimony up until now, but[n]has decided to listen...[n][e]

[msg commu21_lv02]
[s]She seems to believe you a little[n]more knowing that you didn't lie[n]about the Sakura residence...[n][e]

[msg commu21_lv03]
[s]After some incidents with the[n]public, she has begun to see[n]things from a different angle...[n][e]

[msg commu21_lv04]
[s]She said she does not believe[n]everything, but seemed to sense[n]that it is not a lie...[n][e]

[msg commu21_lv05]
[s]She began to suspect another[n]culprit, but wants to know[n]why she was targeted...[n][e]

[msg commu21_lv06]
[s]She has begun to think the[n]Phantom Thieves are just. Or did[n]she have a change of heart...?[n][e]

[msg commu21_lv07]
[s]Sae Rank 7[n]This is a bug.[n][e]

[msg commu21_lv08]
[s]Sae Rank 8[n]This is a bug.[n][e]

[msg commu21_lv09]
[s]Sae Rank 9[n]This is a bug.[n][e]

[msg commu21_lv10]
[s]She reclaimed her conviction,[n]now helping to expose the true[n]evil in broad daylight.[n][e]

[msg commu21_rev]
[s]Sae Doubt[n]This is a bug.[n][e]

[msg commu21_broken]
[s]Sae Broken[n]This is a bug.[n][e]

[msg commu22_help]
[s]World Confidant[n]This is a bug.[n][e]

[msg commu22_rev]
[s]World Confidant Doubt[n]This is a bug.[n][e]

[msg commu22_broken]
[s]World Confidant Broken[n]This is a bug.[n][e]

[msg commu23_help]
[s]High Priestess Arcana Burst.[n]Allows for Shadow analysis[n]and bestows battle skills.[n][e]

[msg commu23_lv09]
[s]After exposing the host, she[n]recognized the police blood[n]flowing within her.[n][e]

[msg commu23_lv10]
[s]Supporting her dream to become[n]a police commissioner, you cheer[n]her on as a comrade in justice.[n][e]

[msg commu24_help]
[s]Empress Arcana Burst.[n]Allows for plant growing[n]and bestows battle skills.[n][e]

[msg commu24_lv09]
[s]She came to an understanding[n]with the president and realized[n]the value of believing in others.[n][e]

[msg commu24_lv10]
[s]She dreams of owning a café. Her[n]gaze is focused on the future,[n]no longer fearing betrayal.[n][e]

[msg commu25_help]
[s]Lovers Arcana Burst.[n]Bestows negotiation skills[n]and battle skills.[n][e]

[msg commu25_lv09]
[s]Seeing Shiho off, she became[n]resolute about her modeling[n]career with your encouragement.[n][e]

[msg commu25_lv10]
[s]She took on her rival in a[n]shoot. She wants to inspire[n]others, like her friend...[n][e]

[msg commu26_help]
[s]Hermit Arcana Burst.[n]Bestows informational[n]support skills.[n][e]

[msg commu26_lv09]
[s]Realizing that she doesn't want[n]to be apart from her friends, her[n]bond with you has grown tighter.[n][e]

[msg commu26_lv10]
[s]After conquering Akihabara,[n]she can do anything now...[n]even hang out with friends.[n][e]

[msg commu27_help]
[s]Fortune Arcana Burst.[n]Fortune telling will bring you[n]good luck if you do as told.[n][e]

[msg commu27_lv09]
[s]As she continues to help the[n]confused members, you support her[n]as a comrade who opposes fate.[n][e]

[msg commu27_lv10]
[s]She set herself a new future,[n]and vowed to alter the fate of[n]the Phantom Thieves as well.[n][e]

[msg commu28_help]
[s]Death Arcana Burst. Provides[n]medicine if you act as a test[n]subject for clinical trials.[n][e]

[msg commu28_lv09]
[s]She declined the offer to work[n]at a hospital and continues[n]her work as the town doctor...[n][e]

[msg commu28_lv10]
[s]While she develops new medicine,[n]she supports the Phantom Thieves[n]as a fellow ally of the weak.[n][e]

[msg commu29_help]
[s]Temperance Arcana Burst. Helps[n]with academics as a teacher,[n]and housework as a maid.[n][e]

[msg commu29_lv09]
[s]The guardians had a change of[n]heart. She quit being a maid and[n]wants a fresh start as a teacher.[n][e]

[msg commu29_lv10]
[s]As she fulfills her role as a[n]teacher, you two form a bond[n]as trustworthy comrades...[n][e]

[msg commu30_help]
[s]Devil Arcana Burst. Articles[n]refine public view of Phantom[n]Thieves and change the Metaverse.[n][e]

[msg commu30_lv09]
[s]She finally unveiled the[n]mastermind behind the case, and[n]you support her despite the risks.[n][e]

[msg commu30_lv10]
[s]She decided to work with the[n]Phantom Thieves as a powerful[n]ally for uncovering social evils.[n][e]

[msg commu31_help]
[s]Star Arcana Burst.[n]Uses shogi skills as battle[n]strategies in the Metaverse.[n][e]

[msg commu31_lv09]
[s]Realizing her lack of skill, she[n]tried to resign from teaching.[n]You pulled her back as a friend...[n][e]

[msg commu31_lv10]
[s]She decided to start fresh to[n]clear her name, while you work[n]to better each other.[n][e]

[msg commu32_help]
[s]Sae Comrade route[n]This is a bug.[n][e]

[msg commu33_help]
[s]Kasumi Help[n]This is a bug.[n][e]

[msg commu33_lv01]
[s]A freshman who does gymnastics.[n]Kasumi wants to talk with you in[n]exchange for teaching you moves.[n][e]

[msg commu33_lv02]
[s]Kasumi's in a slump, having[n]difficulty with her routine. She[n]wants to regain her boldness...[n][e]

[msg commu33_lv03]
[s]Kasumi brought bento for you[n]both. Unsure how to flavor it[n]she made it all curry flavored.[n][e]

[msg commu33_lv04]
[s]In carefully choosing a pair of[n]glasses for her father, Kasumi[n]has begun to regain confidence.[n][e]

[msg commu33_lv05]
[s]She's turned her desire to meet[n]your expectations into her own[n]motivation, to great effect.[n][e]

[msg commu33_lv06]
[s]Apologizing for the deceit, she[n]opened up about her sister. She[n]wants to start anew as Sumire...[n][e]

[msg commu33_lv07]
[s]Feeling down and unable to[n]live up to Kasumi's bold moves,[n]her coach gave her wise words.[n][e]

[msg commu33_lv08]
[s]Sumire decided to go shopping[n]for clothing to express herself.[n]Maybe someone will notice...[n][e]

[msg commu33_lv09]
[s]Sumire realized Kasumi's true[n]feelings, along with her own[n]feelings for [f 4 2]...[n][e]

[msg commu33_lv10]
[s]Sumire succeeded in blending[n]boldness with grace, making a[n]promise to her lover to aim high.[n][e]

[msg commu33_rev]
[s]Sumire Doubt[n]This is a bug.[n][e]

[msg commu33_broken]
[s]Sumire Broken[n]This is a bug.[n][e]

[msg commu34_help]
[s]Kasumi Help[n]This is a bug.[n][e]

[msg commu34_lv09]
[s]After discovering how Kasumi felt,[n]Sumire resolves to be independent.[n]You give her support as her friend.[n][e]

[msg commu34_lv10]
[s]Sumire succeeded in blending[n]boldness with grace, looking at[n]the future with determination.[n][e]

[msg commu35_help]
[s]Maruki Help[n]This is a bug.[n][e]

[msg commu35_lv01]
[s]Maruki suggested counseling to[n][f 4 2] after the struggle[n]with Kamoshida.[n][e]

[msg commu35_lv02]
[s]He was thrilled to see you at the[n]Nurse's Office and offered mental[n]training if you help with research.[n][e]

[msg commu35_lv03]
[s]He spoke on other types of pain,[n]such as heartbreak, and revealed[n]the reason for his research.[n][e]

[msg commu35_lv04]
[s]After being scratched by a cat, he[n]wondered how to heal his heart[n]the same way as a physical wound.[n][e]

[msg commu35_lv05]
[s]Using the law of scarcity, he[n]explained how one's happiness[n]relies on perceptions, true or not.[n][e]

[msg commu35_lv06]
[s]He hit a wall in his research and[n]consulted you. Your advice on the[n]collective unconscious helped.[n][e]

[msg commu35_lv07]
[s]He analyzed the methods of the[n]Phantom Thieves and talked about[n]a world where desires materialize.[n][e]

[msg commu35_lv08]
[s]You and Maruki went to a buffet,[n]where you met his good friend[n]Shibusawa and discussed the past.[n][e]

[msg commu35_lv09]
[s]After talking about his former lover[n]and the tragedy that inspired his[n]research, he vowed to complete it.[n][e]

[msg commu35_lv10]
[s]Maruki's time at Shujin has ended.[n]With conviction, he steps into his[n]future, paper in hand...[n][e]

[msg commu35_rev]
[s]Maruki Doubt[n]This is a bug.[n][e]

[msg commu35_broken]
[s]Maruki Broken[n]This is a bug.[n][e]

[msg commu36_help]
[s]Sumire Doubt[n]This is a bug.[n][e]

[msg commu36_lv01]
[s]A freshman who does gymnastics.[n]Sumire wants to talk with you in[n]exchange for teaching you moves.[n][e]

[msg commu36_lv02]
[s]Sumire's in a slump, having[n]difficulty with her routine. She[n]wants to regain her boldness...[n][e]

[msg commu36_lv03]
[s]Sumire brought bento for you[n]both. Unsure how to flavor it[n]she made it all taste of curry.[n][e]

[msg commu36_lv04]
[s]In carefully choosing a pair of[n]glasses for her father, Sumire[n]has begun to regain confidence.[n][e]

[msg commu36_lv05]
[s]She's turned her desire to meet[n]your expectations into her own[n]motivation, to great effect.[n][e]

[msg commu36_lv06]
[s]Apologizing for the deceit, she[n]opened up about her sister. She[n]wants to start anew as Sumire...[n][e]

[msg commu36_lv07]
[s]Feeling down and unable to[n]live up to Kasumi's bold moves,[n]her coach gave her wise words.[n][e]

[msg commu36_lv08]
[s]Sumire decided to go shopping[n]for clothing to express herself.[n]Maybe someone will notice...[n][e]

[msg commu36_lv09]
[s]Sumire realized Kasumi's true[n]feelings, along with her own[n]feelings for [f 4 2]...[n][e]

[msg commu36_lv10]
[s]Sumire succeeded in blending[n]boldness with grace, making a[n]promise to her lover to aim high.[n][e]

[msg commu36_rev]
[s]Sumire Doubt[n]This is a bug.[n][e]

[msg commu36_broken]
[s]Sumire Broken[n]This is a bug.[n][e]

[msg commu37_help]
[s]Kasumi Help[n]This is a bug.[n][e]

[msg commu37_lv09]
[s]After discovering how Kasumi felt,[n]Sumire resolves to be independent.[n]You give her support as her friend.[n][e]

[msg commu37_lv10]
[s]Sumire succeeded in blending[n]boldness with grace, looking at[n]the future with determination.[n][e]

[msg commu09_02_lv01]
[s]While investigating the Phantom[n]Thieves, he was moved by[n][f 4 2]'s words...[n][e]

[msg commu09_02_lv02]
[s]He invited you to play billiards,[n]and provoked you by using his[n]non-dominant hand.[n][e]

[msg commu09_02_lv03]
[s]Through helping him escape a[n]close call with troublesome fans,[n]you saw his distrust for adults.[n][e]

[msg commu09_02_lv04]
[s]The Detective Prince invited you to[n]his go-to place, where you talked[n]a bit about school life.[n][e]

[msg commu09_02_lv05]
[s]You played a shooting game[n]with him while talking about his[n]childhood dream of being a hero.[n][e]

[msg commu09_02_lv06]
[s]In the bathhouse, he discussed[n]his family and promised to play[n]another round of billiards.[n][e]

[msg commu09_02_lv07]
[s]After defeating him in a game[n]of billiards, he declares that he[n]won't hold back next time.[n][e]

[msg commu09_02_lv08]
[s]You clashed with Akechi in[n]Mementos and siezed victory.[n]He swore not to lose to you again.[n][e]

[msg commu09_02_lv09]
[s]His objective is to get revenge[n]on his father, Shido. After[n]stating that, he attacked...[n][e]

[msg commu09_02_lv10]
[s]You kept your promise to settle his[n]complex issues with Shido. When[n]will the other promise be fulfilled...?[n][e]

[msg commu09_02_rev]
[s]Akechi Doubt[n]This is a bug.[n][e]

[msg commu09_02_broken]
[s]Akechi Broken[n]This is a bug.[n][e]

[msg commu12_02_lv01]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv02]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv03]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv04]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv05]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv06]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv07]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv08]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv09]
[s]The Velvet Room resident vows[n]to continue supporting you.[n][e]

[msg commu12_02_lv10]
[s]Lavenza praises [f 4 2][n]for completing all tasks. She[n]promises her continued support.[n][e]

[msg commu12_02_rev]
[s]Lavenza Doubt[n]This is a bug.[n][e]

[msg commu12_02_broken]
[s]Lavenza Broken[n]This is a bug.[n][e]

[msg const99_d_name]
[s]First Last[n][e]

[msg const99_d]
[s]Confidant explanation[n]Dummy[n][e]

[msg const01_01_name]
[s]First Last[n][e]

[msg const01_01]
[s]Confidant explanation[n]Dummy[n][e]

[msg const02_01_name]
[s]Ryuji Sakamoto[n][e]

[msg const02_01]
[s]A fellow Persona-user and the[n]former star of the track team.[n]He resents selfish adults.[n][e]

[msg const03_01_name]
[s]Morgana[n][e]

[msg const03_01]
[s]An amnesiac talking cat who[n]moved in with you after you[n]met in the Metaverse.[n][e]

[msg const04_01_name]
[s]Ann Takamaki[n][e]

[msg const04_01]
[s]A quarter-American who spent time[n]abroad. She stands up to save those[n]like herself and her friend.[n][e]

[msg const05_01_name]
[s]Yusuke Kitagawa[n][e]

[msg const05_01]
[s]Genius of Japanese art and Kosei High[n]student. He is resentful of adults who[n]leech off the talent of others.[n][e]

[msg const06_01_name]
[s]Makoto Niijima[n][e]

[msg const06_01]
[s]Shujin Academy's student council[n]president. Casting off expectations[n]of her, she joins the group.[n][e]

[msg const07_01_name]
[s]Haru Okumura[n][e]

[msg const07_01]
[s]Third-year student of Shujin Academy[n]and heiress to a conglomerate. She[n]rises to avenge her father.[n][e]

[msg const08_01_name]
[s]Futaba Sakura[n][e]

[msg const08_01]
[s]Genius hacker, one year younger[n]than you. She opened up her[n]heart to the group that saved her.[n][e]

[msg const09_01_name]
[s]Goro Akechi[n][e]

[msg const09_01]
[s]A third-year high school detective[n]from another school. He seeks the[n]culprit of the psychotic breakdowns.[n][e]

[msg const10_01_name]
[s]Sojiro Sakura[n][e]

[msg const10_01]
[s]The owner of Café Leblanc. Serves[n]as your guardian in Tokyo.[n][e]

[msg const11_01_name]
[s]Chihaya Mifune[n][e]

[msg const11_01]
[s]A fortune teller on the streets of[n]Shinjuku. Her predictions are so[n]accurate, it's spooky.[n][e]

[msg const12_01_name]
[s]Justine and Caroline[n][e]

[msg const12_01]
[s]The Twin Wardens of the Velvet Room.[n]Under their master's orders, they test[n]your skills and help you fuse Personas.[n][e]

[msg const13_01_name]
[s]Dummy (Old Caroline)[n][e]

[msg const13_01]
[s]Dummy (Old Caroline)[n][e]

[msg const14_01_name]
[s]Munehisa Iwai[n][e]

[msg const14_01]
[s]A skilled craftsman who owns a[n]shop on Central Street. Agreed to[n]help you out in exchange for info.[n][e]

[msg const15_01_name]
[s]Tae Takemi[n][e]

[msg const15_01]
[s]The doctor of a clinic in Yongen-Jaya[n]who has a bad rep. She cooperates[n]if you help with her trial tests.[n][e]

[msg const16_01_name]
[s]Sadayo Kawakami[n][e]

[msg const16_01]
[s]Your homeroom teacher at Shujin[n]Academy. She offers help if you keep[n]quiet about her job as a maid.[n][e]

[msg const17_01_name]
[s]Ichiko Ohya[n][e]

[msg const17_01]
[s]Journalist who frequents a bar[n]in Shinjuku. She controls public[n]opinion by writing articles.[n][e]

[msg const18_01_name]
[s]Shinya Oda[n][e]

[msg const18_01]
[s]A grade schooler who frequents[n]the arcade. The King of shooters[n]can teach you his ways.[n][e]

[msg const19_01_name]
[s]Hifumi Togo[n][e]

[msg const19_01]
[s]Yusuke's classmate who strives to[n]be a pro shogi player. She teaches[n]you battle strategy through shogi.[n][e]

[msg const20_01_name]
[s]Yuuki Mishima[n][e]

[msg const20_01]
[s]Your classmate who knows your[n]identity. He wants to help with[n]making the world a better place.[n][e]

[msg const21_01_name]
[s]Toranosuke Yoshida[n][e]

[msg const21_01]
[s]An independent election candidate.[n]He teaches you speech skills that[n]are essential for politics.[n][e]

[msg const22_01_name]
[s]Sae Niijima[n][e]

[msg const22_01]
[s]A young, talented prosecutor of the[n]Special Investigations Unit. Makoto's[n]sister and a regular at Leblanc.[n][e]

[msg const23_01_name]
[s]Taichi Nishina[n][e]

[msg const23_01]
[s]A classmate who quit[n]the volleyball team.[n][e]

[msg const24_01_name]
[s]Igor[n][e]

[msg const24_01]
[s]Master of the Velvet Room. Observes[n]and aids you under the pretext of[n]"rehabilitation toward freedom."[n][e]

[msg const25_01_name]
[s]Kasumi Yoshizawa[n][e]

[msg const25_01]
[s]A first-year at Shujin who becomes[n]your apprentice to improve her[n]gymnastics and teach you moves.[n][e]

[msg const26_01_name]
[s]Takuto Maruki[n][e]

[msg const26_01]
[s]A counselor recently hired at[n]Shujin Academy. He reaches out to[n]students to help ease their burdens.[n][e]

[msg const27_01_name]
[s]Sumire Yoshizawa[n][e]

[msg const27_01]
[s]A first-year Persona-user at Shujin.[n]Now free of her actualized delusion,[n]she decides to stay with the team.[n][e]

[msg const28_01_name]
[s]Lavenza[n][e]

[msg const28_01]
[s]A Velvet Room resident who had[n]been split in two by Yaldabaoth.[n]Guides [f 4 2] as her guest.[n][e]

[msg const29_01_name]
[s]Goro Akechi[n][e]

[msg const99_01]
[s]A Persona-user and former foe.[n]After meeting an unclear fate, he[n]reappears to solve new mysteries.[n][e]

[msg Yusuke_Romance_Rank_1]
[s]Yusuke Rank 1 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_2]
[s]Yusuke Rank 2 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_3]
[s]Yusuke Rank 3 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_4]
[s]Yusuke Rank 4 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_5]
[s]Yusuke Rank 5 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_6]
[s]Yusuke Rank 6 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_7]
[s]Yusuke Rank 7 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_8]
[s]Yusuke Rank 8 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_9]
[s]Yusuke Rank 9 Placeholder.[n][e]

[msg Yusuke_Romance_Rank_10]
[s]Yusuke Rank 10 Placeholder.[n][e]

[msg Yusuke_Romance_Reverse]
[s]Yusuke Reverse Placeholder.[n][e]

[msg Yusuke_Romance_Doubt]
[s]Yusuke Doubt Placeholder.[n][e]

[msg Ryuji_Romance_Rank_1]
[s]Ryuji Rank 1 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_2]
[s]Ryuji Rank 2 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_3]
[s]Ryuji Rank 3 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_4]
[s]Ryuji Rank 4 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_5]
[s]Ryuji Rank 5 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_6]
[s]Ryuji Rank 6 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_7]
[s]Ryuji Rank 7 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_8]
[s]Ryuji Rank 8 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_9]
[s]Ryuji Rank 9 Placeholder.[n][e]

[msg Ryuji_Romance_Rank_10]
[s]Ryuji Rank 10 Placeholder.[n][e]

[msg Ryuji_Romance_Reverse]
[s]Ryuji Reverse Placeholder.[n][e]

[msg Ryuji_Romance_Doubt]
[s]Ryuji Doubt Placeholder.[n][e]

[msg Akechi_Romance_Rank_1]
[s]Akechi Rank 1 Placeholder.[n][e]

[msg Akechi_Romance_Rank_2]
[s]Akechi Rank 2 Placeholder.[n][e]

[msg Akechi_Romance_Rank_3]
[s]Akechi Rank 3 Placeholder.[n][e]

[msg Akechi_Romance_Rank_4]
[s]Akechi Rank 4 Placeholder.[n][e]

[msg Akechi_Romance_Rank_5]
[s]Akechi Rank 5 Placeholder.[n][e]

[msg Akechi_Romance_Rank_6]
[s]Akechi Rank 6 Placeholder.[n][e]

[msg Akechi_Romance_Rank_7]
[s]Akechi Rank 7 Placeholder.[n][e]

[msg Akechi_Romance_Rank_8]
[s]Akechi Rank 8 Placeholder.[n][e]

[msg Akechi_Romance_Rank_9]
[s]Akechi Rank 9 Placeholder.[n][e]

[msg Akechi_Romance_Rank_10]
[s]Akechi Rank 10 Placeholder.[n][e]

[msg Akechi_Romance_Reverse]
[s]Akechi Reverse Placeholder.[n][e]

[msg Akechi_Romance_Doubt]
[s]Akechi Doubt Placeholder.[n][e]

[msg Mishima_Romance_Rank_1]
[s]Mishima Rank 1 Placeholder.[n][e]

[msg Mishima_Romance_Rank_2]
[s]Mishima Rank 2 Placeholder.[n][e]

[msg Mishima_Romance_Rank_3]
[s]Mishima Rank 3 Placeholder.[n][e]

[msg Mishima_Romance_Rank_4]
[s]Mishima Rank 4 Placeholder.[n][e]

[msg Mishima_Romance_Rank_5]
[s]Mishima Rank 5 Placeholder.[n][e]

[msg Mishima_Romance_Rank_6]
[s]Mishima Rank 6 Placeholder.[n][e]

[msg Mishima_Romance_Rank_7]
[s]Mishima Rank 7 Placeholder.[n][e]

[msg Mishima_Romance_Rank_8]
[s]Mishima Rank 8 Placeholder.[n][e]

[msg Mishima_Romance_Rank_9]
[s]Mishima Rank 9 Placeholder.[n][e]

[msg Mishima_Romance_Rank_10]
[s]Mishima Rank 10 Placeholder.[n][e]

[msg Mishima_Romance_Reverse]
[s]Mishima Reverse Placeholder.[n][e]

[msg Mishima_Romance_Doubt]
[s]Mishima Doubt Placeholder.[n][e]

[msg Maruki_Romance_Rank_1]
[s]Maruki Rank 1 Placeholder.[n][e]

[msg Maruki_Romance_Rank_2]
[s]Maruki Rank 2 Placeholder.[n][e]

[msg Maruki_Romance_Rank_3]
[s]Maruki Rank 3 Placeholder.[n][e]

[msg Maruki_Romance_Rank_4]
[s]Maruki Rank 4 Placeholder.[n][e]

[msg Maruki_Romance_Rank_5]
[s]Maruki Rank 5 Placeholder.[n][e]

[msg Maruki_Romance_Rank_6]
[s]Maruki Rank 6 Placeholder.[n][e]

[msg Maruki_Romance_Rank_7]
[s]Maruki Rank 7 Placeholder.[n][e]

[msg Maruki_Romance_Rank_8]
[s]Maruki Rank 8 Placeholder.[n][e]

[msg Maruki_Romance_Rank_9]
[s]Maruki Rank 9 Placeholder.[n][e]

[msg Maruki_Romance_Rank_10]
[s]Maruki Rank 10 Placeholder.[n][e]

[msg Maruki_Romance_Reverse]
[s]Maruki Reverse Placeholder.[n][e]

[msg Maruki_Romance_Doubt]
[s]Maruki Doubt Placeholder.[n][e]

[msg Sae_Romance_Rank_1]
[s]Sae Rank 1 Placeholder.[n][e]

[msg Sae_Romance_Rank_2]
[s]Sae Rank 2 Placeholder.[n][e]

[msg Sae_Romance_Rank_3]
[s]Sae Rank 3 Placeholder.[n][e]

[msg Sae_Romance_Rank_4]
[s]Sae Rank 4 Placeholder.[n][e]

[msg Sae_Romance_Rank_5]
[s]Sae Rank 5 Placeholder.[n][e]

[msg Sae_Romance_Rank_6]
[s]Sae Rank 6 Placeholder.[n][e]

[msg Sae_Romance_Rank_7]
[s]Sae Rank 7 Placeholder.[n][e]

[msg Sae_Romance_Rank_8]
[s]Sae Rank 8 Placeholder.[n][e]

[msg Sae_Romance_Rank_9]
[s]Sae Rank 9 Placeholder.[n][e]

[msg Sae_Romance_Rank_10]
[s]Sae Rank 10 Placeholder.[n][e]

[msg Sae_Romance_Reverse]
[s]Sae Reverse Placeholder.[n][e]

[msg Sae_Romance_Doubt]
[s]Sae Doubt Placeholder.[n][e]

[msg Iwai_Romance_Rank_1]
[s]Iwai Rank 1 Placeholder.[n][e]

[msg Iwai_Romance_Rank_2]
[s]Iwai Rank 2 Placeholder.[n][e]

[msg Iwai_Romance_Rank_3]
[s]Iwai Rank 3 Placeholder.[n][e]

[msg Iwai_Romance_Rank_4]
[s]Iwai Rank 4 Placeholder.[n][e]

[msg Iwai_Romance_Rank_5]
[s]Iwai Rank 5 Placeholder.[n][e]

[msg Iwai_Romance_Rank_6]
[s]Iwai Rank 6 Placeholder.[n][e]

[msg Iwai_Romance_Rank_7]
[s]Iwai Rank 7 Placeholder.[n][e]

[msg Iwai_Romance_Rank_8]
[s]Iwai Rank 8 Placeholder.[n][e]

[msg Iwai_Romance_Rank_9]
[s]Iwai Rank 9 Placeholder.[n][e]

[msg Iwai_Romance_Rank_10]
[s]Iwai Rank 10 Placeholder.[n][e]

[msg Iwai_Romance_Reverse]
[s]Iwai Reverse Placeholder.[n][e]

[msg Iwai_Romance_Doubt]
[s]Iwai Doubt Placeholder.[n][e]

[msg Yoshida_Romance_Rank_1]
[s]Yoshida Rank 1 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_2]
[s]Yoshida Rank 2 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_3]
[s]Yoshida Rank 3 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_4]
[s]Yoshida Rank 4 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_5]
[s]Yoshida Rank 5 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_6]
[s]Yoshida Rank 6 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_7]
[s]Yoshida Rank 7 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_8]
[s]Yoshida Rank 8 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_9]
[s]Yoshida Rank 9 Placeholder.[n][e]

[msg Yoshida_Romance_Rank_10]
[s]Yoshida Rank 10 Placeholder.[n][e]

[msg Yoshida_Romance_Reverse]
[s]Yoshida Reverse Placeholder.[n][e]

[msg Yoshida_Romance_Doubt]
[s]Yoshida Doubt Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman]
[s]Akechi_3rdSemester Rank 1 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_2]
[s]Akechi_3rdSemester Rank 2 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_3]
[s]Akechi_3rdSemester Rank 3 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_4]
[s]Akechi_3rdSemester Rank 4 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_5]
[s]Akechi_3rdSemester Rank 5 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_6]
[s]Akechi_3rdSemester Rank 6 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_7]
[s]Akechi_3rdSemester Rank 7 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_8]
[s]Akechi_3rdSemester Rank 8 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_9]
[s]Akechi_3rdSemester Rank 9 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_10]
[s]Akechi_3rdSemester Rank 10 Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_11]
[s]Akechi_3rdSemester Reverse Placeholder.[n][e]

[msg Akechi_3rdSemester_Roman_12]
[s]Akechi_3rdSemester Doubt Placeholder.[n][e]

